[package]
name = "source_bsp_reader"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
regex = "1.11.1"
simple_utils = { path = "../simple_utils" }
source_mdl_mats_finder = { path = "../source_mdl_mats_finder" }